language: go

go:
  - tip

install:
  - go get code.google.com/p/goauth2/oauth
  - go get github.com/garyburd/redigo/redis

script:
  - go build github.com/lighttransport/francine/master
  - go build github.com/lighttransport/francine/worker
  - go build github.com/lighttransport/francine/ltesetup
