language: go

go:
  - tip

install:
  - go get code.google.com/p/goauth2/oauth
  - go get github.com/garyburd/redigo/redis

script:
  - cd $TRAVIS_BUILD_DIR/master && go build
  - cd $TRAVIS_BUILD_DIR/worker && go build 
  - cd $TRAVIS_BUILD_DIR/ltesetup && go build 
