#cloud-config
hostname: lte-master

write_files:
  - path: /home/core/master-setup.sh
    permissions: '0744'
    owner: root:root
    content: |
      #!/usr/bin/env bash
      #
      # Limit log size of journald
      sed 's/#\(SystemMaxUse=\).*/\164M/' -i /etc/systemd/journald.conf
      sed 's/#\(SystemMaxFileSize=\).*/\164M/' -i /etc/systemd/journald.conf

coreos:
  etcd:
    name: lte-master
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  units:
    - name: etcd.service
      command: start
    - name: master-setup.service
      content: |
        [Unit]
        Description=Setup Master node configuration
        After=systemd-journald.service

        [Service]
        ExecStart=/bin/bash /home/core/master-setup.sh

        [Install]
        WantedBy=multi-user.target
    - name: registry.service
      command: start
      content: |
        [Unit]
        Description=Docker Container Registry
        After=docker.service
        Requires=docker.service
        [Service]
        ExecStartPre=/usr/bin/sudo /bin/sh -xc "echo '127.0.0.1 localhost' >> /etc/hosts; exit 0"
        ExecStartPre=/usr/bin/mkdir -p /home/peryaudo/registry
        ExecStart=/usr/bin/docker run -p 5001:5000 -v /home/peryaudo/registry:/tmp registry

        [Install]
        WantedBy=multi-user.target
    - name: ltemaster.service
      command: start
      content: |
        [Unit]
        Description=LTE Master Container
        After=registry.service etcd.service redis.service
        Requires=registry.service etcd.service redis.service
        [Service]
        ExecStartPre=/usr/bin/docker pull 127.0.0.1:5001/lte_master
        ExecStartPre=/bin/sh -xc "/usr/bin/etcdctl set /logentries-token \"<logentries_token>\"; exit 0"
        ExecStartPre=/bin/sh -xc "/usr/bin/etcdctl set /redis-server $private_ipv4:6379; exit 0"
        ExecStartPre=/bin/sh -xc "/usr/bin/etcdctl set /lte-worker-url $private_ipv4:5001/lte_worker; exit 0"
        ExecStart=/usr/bin/docker run -p 80:80 -e ETCD_HOST=172.17.42.1:4001 127.0.0.1:5001/lte_master /bin/master
        Restart=always
        RestartSec=30
        [Install]
        WantedBy=multi-user.target
    - name: ltedemo.service
      command: start
      content: |
        [Unit]
        Description=LTE Demo Container
        After=registry.service etcd.service redis.service ltemaster.service
        Requires=registry.service etcd.service redis.service ltemaster.service
        [Service]
        ExecStartPre=/usr/bin/docker pull 127.0.0.1:5001/lte_demo
        ExecStart=/usr/bin/docker run -p 7000:7000 -e ETCD_HOST=172.17.42.1:4001 -e REST_HOST=$private_ipv4 127.0.0.1:5001/lte_demo /usr/bin/nodejs /tmp/server/server.js
        Restart=always
        RestartSec=30
        [Install]
        WantedBy=multi-user.target
    - name: redis.service
      command: start
      content: |
        [Unit]
        Description=Redis
        After=registry.service
        Requires=registry.service

        [Service]
        ExecStartPre=/usr/bin/docker pull 127.0.0.1:5001/redis
        ExecStart=/usr/bin/docker run -p 6379:6379 127.0.0.1:5001/redis
        Restart=always
        RestartSec=30

        [Install]
        WantedBy=multi-user.target
    - name: send-log.service
      command: start
      content: |
        [Unit]
        Description=Send Log
        [Service]
        ExecStart=/bin/sh -xc "journalctl -o short -f | awk '{ print \"<logentries_token>\", $0; fflush(); }' | ncat data.logentries.com 10000"
        [Install]
        WantedBy=multi-user.target
