#cloud-config
hostname: <hostname>

coreos:
  units:
    - name: lteworker.service
      command: start
      content: |
        [Unit]
        Description=LTE Worker Container

        [Service]
        ExecStartPre=/bin/sh -xc "/usr/bin/docker pull <lte_worker_url>"
        ExecStart=/bin/sh -xc "/usr/bin/docker run -e REDIS_HOST=<redis_server> -e WORKER_NAME=<hostname> -w /home/default <lte_worker_url> /bin/worker"
        Restart=always
        RestartSec=30

        [Install]
        WantedBy=multi-user.target
